from typing import Protocol
from domain.plugin import PluginInstall, CatalogEntry


class PluginRepository(Protocol):
    def list_installs(self, tenant_id: str) -> list[PluginInstall]: ...
    def install(self, tenant_id: str, plugin_id: str, installed_by: str | None) -> None: ...
    def update_status(self, tenant_id: str, plugin_id: str, status: str) -> bool: ...
    def uninstall(self, tenant_id: str, plugin_id: str) -> None: ...
    def get_catalog(self, tenant_id: str) -> list[CatalogEntry]: ...
    def plugin_registered(self, plugin_id: str) -> bool: ...
