from typing import Protocol
from domain.tenant import Tenant, Membership


class TenantRepository(Protocol):
    def get_tenant(self, tenant_id: str) -> Tenant | None: ...
    def get_caller_role(self, tenant_id: str, user_id: str) -> str | None: ...
    def save_settings(self, tenant_id: str, updates: dict) -> Tenant | None: ...
    def list_members(self, tenant_id: str) -> list[Membership]: ...
    def find_user_by_email(self, email: str) -> str | None: ...
    def upsert_member(self, tenant_id: str, user_id: str, role: str) -> None: ...
    def remove_member(self, tenant_id: str, user_id: str) -> None: ...
    def get_membership_with_tenant(self, user_id: str) -> dict | None: ...
