from typing import Protocol
from domain.user import UserProfile, Preferences, TenantPreferences


class UserRepository(Protocol):
    def get_profile(self, user_id: str) -> UserProfile: ...
    def save_profile(self, user_id: str, profile: UserProfile) -> UserProfile: ...
    def get_preferences(self, user_id: str) -> Preferences: ...
    def save_preferences(self, user_id: str, prefs: Preferences) -> Preferences: ...
    def get_primary_tenant_id(self, user_id: str) -> str | None: ...
    def get_tenant_preferences(self, user_id: str, tenant_id: str) -> TenantPreferences: ...
    def save_tenant_preferences(self, user_id: str, tenant_id: str, prefs: TenantPreferences) -> TenantPreferences: ...
